# This projects starts with 30001

TYPE_ID_INTEGER = 30001
TYPE_NAME_INTEGER = "Integer"

TYPE_ID_FLOAT = 30002
TYPE_NAME_FLOAT = "Float"

TYPE_ID_DOUBLE = 30003
TYPE_NAME_DOUBLE = "Double"

TYPE_ID_LONG = 30004
TYPE_NAME_LONG = "Long"

TYPE_ID_BOOLEAN = 30005
TYPE_NAME_BOOLEAN = "Boolean"

TYPE_ID_STRING = 30006
TYPE_NAME_STRING = "String"

TYPE_ID_UUID = 30017
TYPE_NAME_UUID = "Uuid"

TYPE_ID_FILE_PATH = 30020
TYPE_NAME_FILE_PATH = "FilePath"

TYPE_ID_CACHE_KEY = 30023
TYPE_NAME_CACHE_KEY = "CacheKey"

TYPE_ID_DIRECT = 30021
TYPE_NAME_DIRECT = "Direct"

TYPE_ID_CACHED = 30022
TYPE_NAME_CACHED = "Cached"
